---
name: ExampleOS
actions:
  mmdebstrap:
    suite: trixie
    target: rootfs.tar.gz
    setup-hooks:
      - 'sync-in overlay/debian/ /'
    packages:
      - systemd-boot
      - dracut
      - linux-image-amd64
      - ostree
      - ostree-boot
